version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.4.0
    - 7.5.0
    - 7.6.0
  - dependency-name: vuetify
    versions:
    - 2.4.0
    - 2.4.3
    - 2.4.5
  - dependency-name: firebase
    versions:
    - 8.2.1
    - 8.2.5
    - 8.2.9
  - dependency-name: vue-cli-plugin-vuetify
    versions:
    - 2.0.9
    - 2.1.0
    - 2.2.0
  - dependency-name: sass-loader
    versions:
    - 10.1.0
    - 10.1.1
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
    - 4.5.9
  - dependency-name: sass
    versions:
    - 1.32.0
    - 1.32.5
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.11
    - 4.5.9
- package-ecosystem: npm
  directory: "/functions"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: firebase-functions
    versions:
    - 3.13.0
    - 3.13.1
