language: node_js
node_js:
  - 10
cache: yarn
script:
  - yarn lint --no-fix
  - yarn test:unit --coverage
  - yarn storybook:build
  - yarn build
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

before_deploy:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build; else yarn build:staging; fi
  - npm install --global firebase-tools
  - firebase --version
  - cd functions
  - npm install
  - cd ../
deploy:
  - provider: firebase
    skip_cleanup: true
    project: production
    token:
      secure: "p11Qta3QPRbozvUQmMMvoXNeFYN0zgMUlz0kr/Swc1loD64S6ffQ4sy7uLz6LDPLBG+il0ZnqIu9HkmJWD2KE2aYZjrhzbr229tTpl2tIH3P9TDev7C+gI4lSpKuwaKGoU/C1BTAJH4aBJZG/rpHwOYjlOsgZQO0oQQ+lHtgomsM4uUEFvnZPKEmSNy6DK8thXUMd28HNlN86NuVR0v6MqDMlcilxgwAdbh3m2sLZDB/N56ygbqikqcQGA6y3CdGBmaLo3/awIctwvDTp761ea4+D+moJXOmj8q++MR9w3BEUgnKDyfESLhXMCj8nlQblNQihC3hEVIIkceSLWeDlCulXNBpXT9AOcK2eBY5Ayta1V7sw6H3bvD9bfTB0JnOFksnia/xNwDiZSg7jL1hRjRXtCvmRHBxrqH26tHhE8m2+/hHlZc1bDmOP4GqWk1gCmvAb8F3WxRCN4nUACTponLUQClgpyGJK9vLaZwgzeBB1xvhH+Ey44EILwZM89Cc4jW+d9njdNfc2TJnhd6vygwjlqrCWqIcWbyWYS4aE0wbUIZlK9/KlXgZpt1WE+Q67StuYxOFcJP8flBadk/5hXlprp/zOD3tBtnKShDTxUHfX2zVqy49IJAHFC03YWrgvPwVoyIEVU2hDzDXgPRdFiiH8WIh7cHjcM2OnABPvDM="
    on:
      branch: master
  - provider: firebase
    skip_cleanup: true
    project: staging
    token:
      secure: "p11Qta3QPRbozvUQmMMvoXNeFYN0zgMUlz0kr/Swc1loD64S6ffQ4sy7uLz6LDPLBG+il0ZnqIu9HkmJWD2KE2aYZjrhzbr229tTpl2tIH3P9TDev7C+gI4lSpKuwaKGoU/C1BTAJH4aBJZG/rpHwOYjlOsgZQO0oQQ+lHtgomsM4uUEFvnZPKEmSNy6DK8thXUMd28HNlN86NuVR0v6MqDMlcilxgwAdbh3m2sLZDB/N56ygbqikqcQGA6y3CdGBmaLo3/awIctwvDTp761ea4+D+moJXOmj8q++MR9w3BEUgnKDyfESLhXMCj8nlQblNQihC3hEVIIkceSLWeDlCulXNBpXT9AOcK2eBY5Ayta1V7sw6H3bvD9bfTB0JnOFksnia/xNwDiZSg7jL1hRjRXtCvmRHBxrqH26tHhE8m2+/hHlZc1bDmOP4GqWk1gCmvAb8F3WxRCN4nUACTponLUQClgpyGJK9vLaZwgzeBB1xvhH+Ey44EILwZM89Cc4jW+d9njdNfc2TJnhd6vygwjlqrCWqIcWbyWYS4aE0wbUIZlK9/KlXgZpt1WE+Q67StuYxOFcJP8flBadk/5hXlprp/zOD3tBtnKShDTxUHfX2zVqy49IJAHFC03YWrgvPwVoyIEVU2hDzDXgPRdFiiH8WIh7cHjcM2OnABPvDM="
    on:
      branch: staging
