language: node_js

node_js:
  - 10

cache: yarn

script:
  - "yarn storybook:serve &"
  - "yarn lint"
  - "yarn test:unit --coverage"
  - "yarn storybook:build"
  - "yarn test:pupp"
  - "yarn build"
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
