language: node_js
node_js:
  - 10
cache: yarn
script:
  - yarn storybook:serve &
  - yarn lint
  - yarn test:unit --coverage
  - yarn storybook:build
  - yarn test:pupp
  - yarn build
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

before_deploy:
  - npm version patch
  - yarn build
deploy:
  provider: firebase
  token:
    secure: "EuD3wNRppR272LdeD9W0hCLfdqv0mepdNtODnosm6SsL6Tc3P7P45mrMZd4ketr7/0uueRrkI+GgcJTU0cclbyEbm9xx+4C7B8Lodv1HFZLfz0RotGmbySSuJ3VqwMMmIA74AMWITaPtgwq4o4G1f47EImAdM4C0rUNfk0RPnanehcHN0QM+KKT7fEnJxJQ7t38L+ciU/Xac1UhJqTT0nvlEwEaAmfK9pwT4jmTc80YivhyftIUNRArVGk17ZJ8ih3vjtb0/mxOj6GzfZLz57xpk6JbnEQrhIWdy8IIg3XjsLP4JIPGaTOQh2lTvhX8CgsvUX0cwFiUw+TeMx/3Mf8YKyygBJn3pLJLK7qe5B1xKOtAsjfDjjj+iOKB7ZDw34Wky43Rai99KDIryQZ48egvYHWVafvZ0xMYEuTATnauvZ/FVo7iJce0VgdgAqdFvuMjd6vnKQSGJGpVNSlIp6P9BLr3S75PHOWiDCkfSf5vS9JzApu/r3soJ7LaDIxIA8v5TB4NVrcbSvt6NrVhDwog7EZ1yqUiRDTmv1jQDTDam4vFo6EtqStEZ9HJNq4/nRW6DU4j0hCwPpXveLEzMb0NBWDTzMpGLCKJgijr7M2/CL0XYsrV2GbfQZqTaw7XO7LXdKEIKZuwioqNwgRzn+Gi7YTq8aWVWYMchTwLDUrM="
  on:
    branch: master
after_deploy:
  - git push --quiet https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git --tags

env:
  global:
    secure: "bvZWKuwBvpUqMoMMTkTtssQsAbq/pLX6EkMS2IHFylQvUCgltnEvYkMEKFbkII3B58yawxmAoKavaHX4uxSUwEyOnuc4nOXM4PatQLad3rIqoZ3aCudAf84dzZzHkX3nhUyPPYu0aWlFIu2ywz0TWUJaZ0dUHD+3kdrLDRdf5XKurKWbHEEiJ0hOk7lfNlb/iZD5bb3j1LjUi+GAczay6UcrYw/PJbThPqz0OUskr5Gsjk8nPqZ4rFXmMW9GFQS1RDjd5TUbS8Bgh2+JKyCddKApVBrtRAyX0XrOpr7yXPHSIIcshxhtuKTiYwnIhs9SwhSQLwiUJzoPLXWFJmXQ9EY0G1FkGA65vdbcR7mV2K/+fvAll/+CiGt+HXO3jZcqboBDGqnUi0mJzDdJzA5TVNuXBQTSHvX+IPsFrv+BsDsqv5VXLV+2Yx2E2SGb1XssI4dbMgZsT/fkxu31/utv/wyK9GLMjjLOWLOJjWzfnU6HxRYwwOGeZZUAO/m49zust16SHiAlIBtBJ3YIE+8DEyYyvrLgPaWgFrXMTSRbsGUsu6MkWjIDVWb5BK6eD8vzDw5MvYbhI1JNl9IbLZxaMj5giaw7l4BWHURnL50SF2WldjQf2bGvonDjb0btY98HMh5DtMy7dcVcgu5kOl//56uJMmleDmD5r2zVB9PEeMw="

