export const getterTypes = {
  FILES: 'FILES',
  FILE_AUTHORITIES: 'FILE_AUTHORITIES',
  SHARED_FILES: 'SHARED_FILES',
  SHARED_FILE_AUTHORITIES: 'SHARED_FILE_AUTHORITIES'
}

export const actionTypes = {
  LOAD_FILE: 'LOAD_FILE',
  LOAD_FILES: 'LOAD_FILES',
  UPDATE_FILES: 'UPDATE_FILES',
  CREATE_FILE: 'CREATE_FILE',
  DELETE_FILES: 'DELETE_FILES',
  INVITE_USER: 'INVITE_USER'
}

export const mutationTypes = {
  UPDATE_FILES: 'UPDATE_FILES',
  UPDATE_FILE_AUTHORITIES: 'UPDATE_FILE_AUTHORITIES',
  UPDATE_SHARED_FILES: 'UPDATE_SHARED_FILES',
  UPDATE_SHARED_FILE_AUTHORITIES: 'UPDATE_SHARED_FILE_AUTHORITIES',
  CLEAR_FILES: 'CLEAR_FILES'
}
