export const getterTypes = {
  FILES: 'FILES',
  FILE_AUTHORITIES: 'FILE_AUTHORITIES'
}

export const actionTypes = {
  LOAD_FILES: 'LOAD_FILES',
  UPDATE_FILES: 'UPDATE_FILES',
  CREATE_FILE: 'CREATE_FILE',
  DELETE_FILES: 'DELETE_FILES'
}

export const mutationTypes = {
  UPDATE_FILES: 'UPDATE_FILES',
  CLEAR_FILES: 'CLEAR_FILES',
  UPDATE_FILE_AUTHORITIES: 'UPDATE_FILE_AUTHORITIES'
}
