export const getterTypes = {
  USER: 'USER',
  AUTHORITY_LOADING: 'AUTHORITY_LOADING',
  CAN_WRITE: 'CAN_WRITE'
}

export const actionTypes = {
  LOAD_USER: 'LOAD_USER',
  SIGN_OUT: 'SIGN_OUT',
  SET_AUTHORITY_LOADING: 'SET_AUTHORITY_LOADING',
  DELETE_USER: 'DELETE_USER'
}

export const mutationTypes = {
  SET_USER: 'SET_USER',
  SET_AUTHORITY_LOADING: 'SET_AUTHORITY_LOADING'
}
