export const getterTypes = {
  NODES: 'NODES',
  SELECTED_NODES: 'SELECTED_NODES',
  FILE_KEY: 'FILE_KEY'
}

export const actionTypes = {
  DISCONNECT: 'DISCONNECT',
  LOAD_NODES: 'LOAD_NODES',
  UPDATE_NODES: 'UPDATE_NODES',
  SET_SELECTED_NODES: 'SET_SELECTED_NODES',
  CLEAR_SELECT: 'CLEAR_SELECT'
}

export const mutationTypes = {
  UPDATE_NODES: 'UPDATE_NODES',
  SET_SELECTED_NODES: 'SET_SELECTED_NODES',
  SET_FILE_KEY: 'SET_FILE_KEY',
  CLEAR_NODES: 'CLEAR_NODES'
}
