export const getterTypes = {
  COMMENTS: 'COMMENTS',
  FILE_KEY: 'FILE_KEY',
}

export const actionTypes = {
  DISCONNECT: 'DISCONNECT',
  LOAD_COMMENTS: 'LOAD_COMMENTS',
  UPDATE_COMMENTS: 'UPDATE_COMMENTS',
}

export const mutationTypes = {
  UPDATE_COMMENTS: 'UPDATE_COMMENTS',
  SET_FILE_KEY: 'SET_FILE_KEY',
  CLEAR_COMMENTS: 'CLEAR_COMMENTS',
}
